version: "3.8"
services:
  trade-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trade-web
    environment:
      REPO_DIR: /srv/trade-repo
      OUTPUT_DIR: /data/captures
      # You can switch to your fork any time:
      # REPO_GIT: https://github.com/YourUser/options-trading-assistant
    ports:
      - "8000:8000"
    volumes:
      - ./data/captures:/data/captures
      - ./data/trade-repo:/srv/trade-repo
    restart: unless-stopped
